export const POST_COMMENT_CREATE_REQUEST = 'POST_COMMENT_CREATE_REQUEST';
export const POST_COMMENT_CREATE_SUCCESS = 'POST_COMMENT_CREATE_SUCCESS';
export const POST_COMMENT_CREATE_ERROR = 'POST_COMMENT_CREATE_ERROR';

