export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const POSTS_LIKED_REQUEST = 'POSTS_LIKED_REQUEST';
export const POSTS_LIKED_SUCCESS = 'POSTS_LIKED_SUCCESS';
export const POSTS_LIKED_ERROR = 'POSTS_LIKED_ERROR';
export const PAGE_CHANGED = 'PAGE_CHANGED';
