export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const POST_LIKED_REQUEST = 'POST_LIKED_REQUEST';
export const POST_LIKED_SUCCESS = 'POST_LIKED_SUCCESS';
export const POST_LIKED_ERROR = 'POST_LIKED_ERROR';
